---
app:
  name: OpenDAX
  domain: zigmacoin.com
  subdomain: www
  show_landing: true
render_protect: false
csrfEnabled: false
ssl:
  enabled: true
  email: support@zigmacoin.com
updateVersions: false
images:
  peatio: quay.io/openware/peatio:2.6.28
  barong: quay.io/openware/barong:2.6.19
  frontend: frontend/baseapp:2.6.0
  tower: quay.io/openware/tower:2.6.36
  rango: quay.io/openware/rango:2.6.1
finex:
  enabled: false
  image: quay.io/openware/finex:2.6.12
  license_key: changeme
vendor:
  frontend: git@github.com:openware/baseapp.git
kyc:
  provider: local
  authorization_token: 891e65a30a09a240502b98c17dc9df79ebf5
  sandbox_mode: true
  api_endpoint: https://api.kycaid.com/
vault:
  root_token: s.vYGhZaeR2JJbpCUG3tcM5cSg
  peatio_rails_token: s.VV3XBZsirFcxhrSaImg4dRqc
  peatio_crypto_token: s.ya0INy6zahDgY6Hfq2ibdNdS
  peatio_upstream_token: s.hZhEcGpzw4RIreYp3l2j8i1L
  peatio_matching_token: s.a6ej3Mi8MbXGQ2BDMPQsh2tQ
  barong_token: s.FvjC6BfZwnnW4B59delaXTJK
  finex_engine_token: s.VyBZqQI73bKGSC9fk2FDxRfv
database:
  host: db
  adapter: mysql
  port: 3306
  user: root
  password: changeme
storage:
  provider: Google
  bucketName: opendax-barong-docs-bucket
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  accessKey: changeme
  secretKey: changeme
  signatureVersion: '2'
twilio:
  enabled: true
  phone_number: "+14159695720"
  account_sid: SK81b8869fade6deb591ec7d6d8f98d491
  auth_token: wbDvCQ460SBkis0woebto2OzlMpeJpjv
gaTrackerKey: ''
captcha:
  type: google
  siteKey: 6LdrI2IaAAAAAPtYzoo-I_CpvTFLd2Rh12mediWV
  secretKey: 6LdrI2IaAAAAAGsAdA8lwbXTZ16kKZZepayAoEF8
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: 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
  sender_email: support@zigmacoin.com
  sender_name: Postmaster
  sender_logo: https://storage.googleapis.com/public_peatio/logo.png
wallets:
  eth:
  - kind: deposit
    address: changeme
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: changeme
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: changeme
    max_balance: 1000.0
    secret: changeme
  btc:
  - kind: deposit
    address: changeme
    max_balance: 0.0
  - kind: hot
    address: changeme
    max_balance: 100.0
  - kind: warm
    address: changeme
    max_balance: 1000.0
parity:
  network: testnet
  address: parity
  rpcport: 8545
  port: 30303
bitcoind:
  enabled: false
  rpcuser: admin
  rpcpassword: changeme
  address: bitcoind
  network: testnet
  rpcport: 18332
  port: 18333
litecoind:
  rpcuser: admin
  rpcpassword: changeme
  address: litecoind
  network: testnet
  rpcport: 19332
  port: 19335
terraform:
  credentials: "~/safe/opendax.json"
  project: example-opendax
  region: europe-west4
  zone: europe-west4-a
  instance_name: opendax-cloud
  machine_type: n1-standard-4
  image: debian-cloud/debian-9
